### ISSUE TITLE
Can't read Firestore timestamp field as a DateTime

### ISSUE THREAD

**Issue by gazialankus** [pulyaevskiy/firebase-admin-interop#29]
In Firestore, I have a "time" field with the type timestamp.

I try to read it like this: `snapshot.data.getDateTime("time")` (I can read other (string) fields just fine)

Here is the exception I get:
```
_AssertionError {
  message: 'Invalid value provided to DocumentData0.getDateTime().',
  '$thrownJsError': 
   { Assertion failed: "Invalid value provided to DocumentData0.getDateTime()."
       at wrapException (/user_code/build/node/index.dart.js:1458:17)
       at assertThrow (/user_code/build/node/index.dart.js:2000:15)
       at DocumentData0.getDateTime$1 (/user_code/build/node/index.dart.js:8487:13)
       at /user_code/build/node/index.dart.js:9378:74
       at _wrapJsFunctionForAsync_closure.$protected (/user_code/build/node/index.dart.js:3736:15)
       at _wrapJsFunctionForAsync_closure.call$2 (/user_code/build/node/index.dart.js:4029:14)
       at _awaitOnObject_closure.call$1 (/user_code/build/node/index.dart.js:4017:34)
       at _RootZone.runUnary$2$2 (/user_code/build/node/index.dart.js:5268:20)
       at _Future__propagateToListeners_handleValueCallback.call$0 (/user_code/build/node/index.dart.js:4609:55)
       at _Future__propagateToListeners (/user_code/build/node/index.dart.js:4418:108)
     dartException: [Circular],
     name: '',
     '$cachedTrace': _StackTrace { _exception: [Circular], _trace: null } } }
```

I removed the assert line from the library, which now gives this exception: 

```
JsNoSuchMethodError {
  _message: 'receiver.getTime is not a function',
  _method: 'getTime',
  _receiver: undefined,
  '$thrownJsError': 
   { TypeError: receiver.getTime is not a function
       at UnknownJavaScriptObject.getTime$0 (/user_code/build/node/index.dart.js:767:25)
       at J.getTime$0$x (/user_code/build/node/index.dart.js:9521:41)
       at DocumentData0.getDateTime$1 (/user_code/build/node/index.dart.js:8478:16)
       at /user_code/build/node/index.dart.js:9368:74
       at _wrapJsFunctionForAsync_closure.$protected (/user_code/build/node/index.dart.js:3727:15)
       at _wrapJsFunctionForAsync_closure.call$2 (/user_code/build/node/index.dart.js:4020:14)
       at _awaitOnObject_closure.call$1 (/user_code/build/node/index.dart.js:4008:34)
       at _RootZone.runUnary$2$2 (/user_code/build/node/index.dart.js:5259:20)
       at _Future__propagateToListeners_handleValueCallback.call$0 (/user_code/build/node/index.dart.js:4600:55)
       at _Future__propagateToListeners (/user_code/build/node/index.dart.js:4409:108)
     '$cachedTrace': _StackTrace { _exception: [Circular], _trace: null } } }
```

When I try to read this field as a string, here's what I get: 

```
CastErrorImplementation {
  message: 'CastError: Instance of \'UnknownJavaScriptObject\': type \'UnknownJavaScriptObject\' is not a subtype of type \'String\'',
  '$thrownJsError': 
   { CastError: Instance of 'UnknownJavaScriptObject': type 'UnknownJavaScriptObject' is not a subtype of type 'String'
       at wrapException (/user_code/build/node/index.dart.js:1454:17)
       at stringTypeCast (/user_code/build/node/index.dart.js:1886:15)
       at /user_code/build/node/index.dart.js:9346:52
       at _wrapJsFunctionForAsync_closure.$protected (/user_code/build/node/index.dart.js:3723:15)
       at _wrapJsFunctionForAsync_closure.call$2 (/user_code/build/node/index.dart.js:4016:14)
       at _awaitOnObject_closure.call$1 (/user_code/build/node/index.dart.js:4004:34)
       at _RootZone.runUnary$2$2 (/user_code/build/node/index.dart.js:5255:20)
       at _Future__propagateToListeners_handleValueCallback.call$0 (/user_code/build/node/index.dart.js:4596:55)
       at _Future__propagateToListeners (/user_code/build/node/index.dart.js:4405:108)
       at _Future__asyncComplete_closure.call$0 (/user_code/build/node/index.dart.js:4508:11)
     dartException: [Circular],
     name: '',
     '$cachedTrace': _StackTrace { _exception: [Circular], _trace: null } } }
```

**Comment by pulyaevskiy** [comment]
Firestore timestamps are not returned as Strings, but as instances of JS `Date` class so I doubt that reading as String would work.

We do have tests for handling Date objects though, so this looks strange.

In what context are you using admin interop? Together with Firebase functions interop or standalone?

It would help a little bit to know versions of Dart SDK and Node.js you are using. And maybe a simple code snippet.

I'd also suggest to double check in the Firebase Console that the field type is actually Date on that document.

**Comment by pulyaevskiy** [comment]
> How do I get more info about this object in the date variable here? This is Dart but it prints [object Object]...

You can try and use either `objectKeys` or `dartify` functions from `node_interop` package. This would give an idea about the object's structure.

Let me know if it works!

**Comment by gazialankus** [comment]
Great, thanks for the tip! And, here's our object in question: 
`{_seconds: 1538254800, _nanoseconds: 0}`
Do you have any idea about this? Should we just see if it has these fields and use these to create a DateTime?

**Comment by gazialankus** [comment]
I see these two fields over here, maybe it would help: https://github.com/firebase/firebase-admin-node/issues/292

**Comment by pulyaevskiy** [comment]
Oh, hmm. Looks like this maybe a recent change.

Could you share version of firebase-admin-node you have in your package.json and package.lock?

**Comment by gazialankus** [comment]
My package.json has `"firebase-admin": "~5.13.0",` but I don't see a package.lock around. I found functions/node_modules/firebase-admin/package.json, which has this line: `  "_resolved": "https://registry.npmjs.org/firebase-admin/-/firebase-admin-5.13.1.tgz",` so it looks like it's 5.13.1.

**Comment by pulyaevskiy** [comment]
Ok, thanks.

I suspect if you rollback to `"firebase-admin": "5.11.0"` then datetime stuff should work (I see test suite still passed with that version).

Though this is just to unblock you for now. We should definitely upgrade to latest as soon as possible.

I'm currently quite a bit overloaded with work so can't promise timely updates here. You could always submit a PR as well if you are interested.

Either way, thanks for reporting this!

**Comment by pulyaevskiy** [comment]
Yeah, pretty much all of the _is* methods are hacks so you solution looks "ok". :)

Definitely, feel free to submit a PR with your change.

**Comment by gazialankus** [comment]
Ok thanks. I just submitted it:)

**Comment by gazialankus** [comment]
createTime and updateTime are also affected, they are not coming in as strings anymore. I'll take your advice and revert to the old firebase-admin for the time being.

**Comment by gazialankus** [comment]
Reverting back didn't work out so well. I shared my situation with a PR in case it may be helpful.
