### ISSUE TITLE
Error: not supported

### ISSUE THREAD

**Issue by redsolver** [pulyaevskiy/firebase-admin-interop#38]
Tried this code in my "main.dart":
```dart
final serviceAccountKeyFilename = 'adminsdk.json';
final admin = FirebaseAdmin.instance;
final cert = admin.certFromPath(serviceAccountKeyFilename);
final app = admin.initializeApp(new AppOptions(
  credential: cert
));
final firestore = app.firestore();
firestore.settings(FirestoreSettings(timestampsInSnapshots: true));

await firestore.collection('notification').add(DocumentData.fromMap({'Hello':'World'}));
```
Got this error:
```
/home/redsolver/AndroidStudioProjects/aesapp_server/build/packages/$sdk/dev_compiler/common/dart_sdk.js:4857
  throw obj;
  ^

Error: not supported
    at GoogleProtoFilesRoot.loadSync (/home/redsolver/AndroidStudioProjects/aesapp_server/node_modules/protobufjs/src/root.js:234:15)
    at Object.loadSync (/home/redsolver/AndroidStudioProjects/aesapp_server/node_modules/protobufjs/src/index-light.js:69:17)
    at GrpcClient.loadProto (/home/redsolver/AndroidStudioProjects/aesapp_server/node_modules/firebase-admin/node_modules/google-gax/build/src/grpc.js:159:54)
    at new FirestoreClient (/home/redsolver/AndroidStudioProjects/aesapp_server/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/v1beta1/firestore_client.js:96:42)
    at ClientPool.pool_1.ClientPool [as clientFactory] (/home/redsolver/AndroidStudioProjects/aesapp_server/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:736:28)
    at ClientPool.acquire (/home/redsolver/AndroidStudioProjects/aesapp_server/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/pool.js:56:35)
    at ClientPool.run (/home/redsolver/AndroidStudioProjects/aesapp_server/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/pool.js:94:29)
    at _clientInitialized.then (/home/redsolver/AndroidStudioProjects/aesapp_server/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:725:68)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by redsolver** [comment]
Used DDC instead of dart2js
