### ISSUE TITLE
Firestore not working

### ISSUE THREAD

**Issue by arrrrny** [pulyaevskiy/firebase-admin-interop#53]
I successfully add data to cloud realtime database, When I try cloud firestore with same config, I get below error:

  final serviceAccountKeyFilename = 'firebase_service_account.json';
  final admin = FirebaseAdmin.instance;
  final cert = admin.certFromPath(serviceAccountKeyFilename);
  final app = admin.initializeApp(
      new AppOptions(credential: cert, databaseURL: "*****.firebaseio.com"));
  app.firestore().settings(FirestoreSettings(timestampsInSnapshots: true));
  final ref = app.firestore().document('/price/VLZzbUplZyufGlYoHrzV');
  var snapshot = await ref.get();
  print(snapshot.data);

(node:21429) UnhandledPromiseRejectionWarning: Error: Error: not supported
    at Object.throw_ [as throw] (/Users/arrrrny/Developer/firebase-admin-interop/build/packages/$sdk/dev_compiler/common/dart_sdk.js:4592:9)
    at async._AsyncCallbackEntry.new.callback (/Users/arrrrny/Developer/firebase-admin-interop/build/packages/$sdk/dev_compiler/common/dart_sdk.js:28609:39)
    at Object._microtaskLoop (/Users/arrrrny/Developer/firebase-admin-interop/build/packages/$sdk/dev_compiler/common/dart_sdk.js:25268:11)
    at _startMicrotaskLoop (/Users/arrrrny/Developer/firebase-admin-interop/build/packages/$sdk/dev_compiler/common/dart_sdk.js:25274:11)
    at /Users/arrrrny/Developer/firebase-admin-interop/build/packages/$sdk/dev_compiler/common/dart_sdk.js:25349:7
(node:21429) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21429) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by arrrrny** [comment]
Strangely, changing the build to use dart2js worked fine.
